### PR TITLE
update StateMachines 

### PR DESCRIPTION
**Pull request by jhoo2458**
Reference from NVMain.
1. Ranks/StandardRank/StandardRank.cpp (ln 943 ~ 997 )
 The ' * devicecount' has been added as a ' * num_dev'.

2. src/SubArray.cpp (ln 414~ 416, ln 551, ln 917 ~ 919)
 The ' / BANKS ' has been added as a ' / num_banks ' .

### CODE REVIEW

**Review by harrylee365 — CHANGES_REQUESTED** [review]
Please revise the followings:
1. Please keep **setup_currents( )** as it is, rather than adding the argument. 
2. Please use je->info->get_banks( ) for getting num_banks in **setup_currents( )**
3. num_banks in **setup_currents( )** should be get_banks * get_bankgroups( ) in our simulator.
4. Please check compilation before pulling the request
Thanks

**Review by jhoo2458 — COMMENTED** [review]
I have revised it accroding to the review.
And confirmed that there was no problem with the build.
Thank you.

**Comment by jhoo2458** [comment]
Modified 'num_banks' to 'num_all_banks'.

**Review by jhoo2458 — COMMENTED** [review]
Modified 'num_banks' to 'num_all_banks'.

**Pull request merged**
